name: plalign
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.83
  - numpy=1.21.5    
  - numpy==1.26.4
  - pandas==2.2.1
  - python=3.12
  - streamlit=1.8.1
  - plotly==5.20.0
  - mappy==2.28
