name: plalign
channels:
  - https://repo.anaconda.com/pkgs/main/linux-64 
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://conda.anaconda.org/bioconda/linux-64 
  - https://conda.anaconda.org/plotly/linux-64 
dependencies:
  - biopython=1.83
  - mappy==2.28
  - plotly==5.20.0
